import type { Deck } from './types'

/**
 * The deck that gets presented and published — `DEFAULT_DECK` in
 * `src/lib/decks.ts` names this file.
 *
 * `satisfies Deck` rather than a type annotation: it checks the whole deck
 * against the contract while keeping the literal's own narrow types, so a
 * misspelled archetype or a `tone` that is not a tone is an error here rather
 * than a slide that renders the wrong thing on stage.
 */
const deck = {
  meta: {
    mark: "Designing with AI (highly opinionated)",
  },
  items: [
    {
      type: "cover",
      id: "designing-with-ai",
      chapter: "Designing with AI",
      title: "Designing with AI, **opinionated**.",
      subtitle: "For developers who enslave the AI-agents, and art is not their way of life.",
    },
    {
      type: "keypoints",
      id: "what-we-cover-today",
      chapter: "What we cover today",
      title: "What we are going to **cover** today",
      points: [
        "Why most of the initial prompts fail",
        "How to express your design intent",
        "How to know what is wrong",
        "My working loop (for now)",
        "Hidden gems, not hype",
      ],
    },
    {
      type: "divider",
      id: "why-prompts-fail",
      chapter: "Why prompts fail",
      number: "01",
      split: "golden-flip",
      title: "Why most of the initial prompts **fail**.",
      note: "Generic prompt = Generic failure",
      list: [
        "AI coding tools can build interfaces incredibly fast.",
        "The problem is that they often build the same interface over and over again. (AI-Slob)",
        "Most AI-generated interfaces fail for the same reason: the prompt gives the model too much freedom.",
      ],
      marker: "bullet",
    },
    {
      type: "cards",
      id: "three-prompts-three-defaults",
      chapter: "Three prompts, three defaults",
      title: "Three prompts, three **defaults**.",
      note: "When you give too much freedom to the AI, it defaults to generic patterns. When you give too much constraints, it struggles to follow them.",
      quoted: true,
      cards: [
        {
          title: "Create a modern dashboard.",
          subtitle: "The AI hears",
          points: [
            "Use the most statistically common dashboard pattern.",
            "That usually means cards, rounded corners, blue accents, generic navigation, neutral typography, and predictable spacing."
          ],
        },
        {
          title: "Make this look premium.",
          subtitle: "What you get",
          points: [
            "That phrase is too vague.",
            "It gives the model permission to fall back on generic patterns.",
            "Gradients, floating icons, fake product mockups",
            "Badge labels, symmetrical feature sections",
          ],
        },
        {
          title: "Use exactly 16px padding, 8px radius, three columns, blue buttons…",
          subtitle: "The AI hears",
          points: [
            "Follow the instructions even when they conflict with the problem.",
            "Specs replace judgement: the numbers get met and the layout stops making sense.",
          ],
        },
      ],
    },
    {
      type: "callouts",
      id: "you-already-know-this-look",
      theme: "light",
      chapter: "You already know this look",
      title: "You already know this **look**.",
      image: {
        src: "showcase/slop-specimen.png",
        alt: "A generic SaaS landing page: centered hero on a purple-blue gradient, a small BETA badge, three identical feature cards below.",        
      },
      points: [
        { text: "Overused fonts: Inter, Roboto, Arial", pin: { x: 24, y: 25 } },
        { text: "Purple-blue gradients with no brand logic", pin: { x: 13, y: 31 } },
        { text: "Repeated three-card grids", pin: { x: 82, y: 58 } },
        { text: "Centered hero sections, weak hierarchy", pin: { x: 50, y: 44 } },
        { text: "An eyebrow label over every heading: BETA, NEW", pin: { x: 44, y: 16 } },
        { text: "Too many nested cards, low-contrast gray text", pin: { x: 18, y: 73 } },
        { text: "Heavy animation using transition: all" },
        { text: "Em dashes everywhere — including this one" },
      ],
      status: "How many times you seen this? Be honest.",
    },
    {
      type: "keypoints",
      id: "seven-things-to-prepare",
      chapter: "Seven things to prepare",
      title: "Seven things to **prepare** before you type.",
      marker: "number",
      split: "golden-flip",
      points: [
        "Product context — what this thing is, and who pays for it",
        "User — who is on the other side of the screen",
        "Hierarchy — what has to be read first, second, last",
        "References — the work you want it to resemble",
        "Constraints — the fonts, colors, and patterns it may not leave",
        "Priorities — what gives way when two of these collide",
        "Success criteria — how you will know the result is right",
      ],
    },
    {
      type: "divider",
      id: "express-your-design-intent",
      chapter: "Express your design intent",
      number: "02",
      split: "golden-flip",
      marker: "bullet",
      title: "How to express your design **intent**.",
      note: "Every studio writes a brand book. This one is written for a reader that cannot be briefed in a meeting: files the agent reads before it writes.",
      list: [
        "A longer prompt does not fix this. The next session starts from zero again.",
        "What the model needs is not more words. It is fewer choices.",
        "So the constraints get written down once, in the repo, where every session finds them.",
      ],
    },
    {
      type: "keypoints",
      id: "what-makes-intent-actionable",
      theme: "light",
      chapter: "What makes intent actionable",
      title: "What makes design intent **actionable**?",
      marker: "bullet",
      split: "golden-flip",
      points: [
        "Audience — who it is for, in one sentence",
        "Purpose — the job the screen does for them",
        "Hierarchy — the order the eye is meant to travel",
        "Visual direction — type, color, and density, named not implied",
        "Interaction rules — what responds, and how it responds",
        "Anti-patterns — the moves it is not allowed to make",
      ],
    },
    {
      type: "cards",
      id: "the-brand-book-in-two-files",
      chapter: "The brand book, in two files",
      title: "The brand book, in two **files**.",
      note: "*based on impeccable.",
      cards: [
        {
          title: "PRODUCT.md",
          subtitle: "Who it serves, and why",
          points: [
            "Users and their situation",
            "Purpose and constraints to preserve",
            "Open questions, marked as open",
            "Written by ```/impeccable init```",
          ],
        },
        {
          title: "DESIGN.md",
          subtitle: "How it looks, and why",
          points: [
            "Token values in YAML frontmatter",
            "Prose on how each value is used",
            "Component rules, Do's and Don'ts",
            "Written by ```/impeccable document```",
          ],
        },
      ],
    },
    {
      type: "codeui",
      id: "product-md-anatomy",
      chapter: "PRODUCT.md anatomy",
      title: "**PRODUCT.md** anatomy",
      file: "PRODUCT.md",
      href: "https://github.com/ncanakturk-3dU/presentation-llm-for-design/blob/main/PRODUCT.md",
      lang: "md",
      code: "# Product\n<!-- impeccable:product-schema 1 -->\n\n## Platform                      web\n## Stack                         ⋯ 1 line\n## Users                         ⋯ 1 line\n## Product Purpose               ⋯ 1 line\n## Positioning                   ⋯ 1 line\n## Operating Context             ⋯ 3 lines\n## Capabilities and Constraints  ⋯ 6 lines\n## Brand Commitments             ⋯ 3 lines\n## Evidence on Hand              ⋯ 12 lines\n## Product Principles            ⋯ 5 lines\n## Accessibility & Inclusion     ⋯ 3 lines",
      preview: {
        title: "Structure details: (omit, don't pad)",
        buttons: [],
        rows: [
          { label: "Platform", detail: "web, ios, android or adaptive." },
          { label: "Stack", detail: "Greenfield only; else the repo answers." },
          { label: "Users", detail: "Who, their situation, their job." },
          { label: "Product Purpose", detail: "What it does, and what success is." },
          { label: "Positioning", detail: "The claim no neighbour could copy." },
          { label: "Operating Context", detail: "Where and how it is really used." },
          { label: "Capabilities and Constraints", detail: "Functionality, limits, open decisions." },
          { label: "Brand Commitments", detail: "Name, voice, binding assets." },
          { label: "Evidence on Hand", detail: "Real material — and the absences." },
          { label: "Product Principles", detail: "Three to five durable rules." },
          { label: "Accessibility & Inclusion", detail: "A known need, or a standard." },
        ],
      },
      note: "Written by ```/impeccable init``` — and **only** that: no palette, no type, no layout. A section with nothing confirmed behind it is omitted, not padded. This deck's own, 73 lines, folded.",
    },
    {
      type: "codeui",
      id: "design-md-anatomy",
      chapter: "DESIGN.md anatomy",
      title: "**DESIGN.md** anatomy",
      file: "DESIGN.md",
      href: "https://github.com/ncanakturk-3dU/presentation-llm-for-design/blob/main/DESIGN.md",
      lang: "md",
      code: "---\nname: LLM for Design\ndials: { variance: 7, motion: 3, density: 4 }\ncolors:      ⋯ 18 tokens\ntypography:  ⋯ 6 roles\ncomponents:  ⋯ 9 specs\n---\n\n## Overview           ⋯ 13 lines\n## Colors             ⋯ 18 lines\n## Typography         ⋯ 13 lines\n## Layout             ⋯ 4 lines\n## Elevation & Depth  ⋯ 8 lines\n## Shapes             ⋯ 1 line\n## Components         ⋯ 22 lines\n## Do's and Don'ts    ⋯ 20 lines",
      preview: {
        title: "Structure details: (order matters)",
        buttons: [],
        rows: [
          { label: "1. Overview", detail: "What the product is, who it is for, how it should feel." },
          { label: "2. Colors", detail: "The palette by role: ground, ink, one accent." },
          { label: "3. Typography", detail: "Families, sizes, weights, line heights." },
          { label: "4. Layout", detail: "Grid, spacing scale, breakpoints." },
          { label: "5. Elevation & Depth", detail: "Shadows and layers: what floats over what." },
          { label: "6. Shapes", detail: "Corner radii, borders, icon shape language." },
          { label: "7. Components", detail: "Buttons, fields, cards and every state they take." },
          { label: "8. Do's and Don'ts", detail: "The traps, written down instead of learned twice." },
        ],
      },
      note: "The open DESIGN.md spec, from Google Labs, Apache 2.0, still alpha. Unknown sections are preserved rather than rejected. This deck's own DESIGN.md, 267 lines, folded.",
    },
    {
      type: "cards",
      id: "three-ways-to-get-a-brand-book",
      chapter: "Three ways to get a brand book",
      title: "Three ways to get a brand **book**.",
      cards: [
        {
          title: "From a site you admire",
          subtitle: "skillui",
          points: [
            "```skillui --url https://site.com```",
            "Static analysis. No AI, no API key.",
            "Emits DESIGN.md, JSON tokens, shots",
            "Read more: [skillui.vercel.app](https://skillui.vercel.app)",
          ],
        },
        {
          title: "From your own codebase",
          subtitle: "impeccable",
          points: [
            "```/impeccable document```",
            "Reads tokens, styles, components and the rendered page",
            "Read more: [impeccable.style](https://impeccable.style)",
          ],
        },
        {
          title: "From a ready-made catalog",
          subtitle: "getdesign.md",
          points: [
            "550+ analyses of real sites",
            "Pick one, drop it in the repo",
            "Read more: [getdesign.md](https://getdesign.md)",
          ],
        },
      ],
    },
    {
      type: "keypoints",
      id: "what-to-review-from-design-md",
      theme: "light",
      chapter: "What to review from DESIGN.md",
      title: "What **you** should review from **DESIGN.md**.",
      marker: "bullet",
      split: "golden-flip",
      points: [
        "Read the principles, not just the rules",
        "Check compatibility with your product",
        "Find conflicts and remove over-specific instructions",
        "Test it on 2–3 real screens"        
      ],
    },
    {
      type: "keypoints",
      id: "establish-a-design-contract",
      chapter: "Establish a design contract",
      title: "Before developing your first screen, establish a design **contract**.",
      marker: "none",
      points: [
        "Reduce ambiguous design decisions by making intent persistent and explicit.",
        "The contract is the two files: `PRODUCT.md` and `DESIGN.md`.",
      ],
    },
    {
      type: "divider",
      id: "how-to-know-what-is-wrong",
      chapter: "How to know what is wrong",
      number: "03",
      split: "golden-flip",
      marker: "bullet",
      title: "How to know what is **wrong**.",
      note: "PRODUCT.md and DESIGN.md describe what we intended to build. They do not tell us whether the result actually works.",
      list: [
        "Intent is not evidence. An agent can follow the spec and still miss the context.",
        "And you cannot name a failure without knowing what right looks like first.",
        "Right comes from three places: principles, conventions, and what good products already do.",
        "Then the check is worth running: metric, evidence, severity, finding.",
      ],
    },
    {
      type: "keypoints",
      id: "do-not-reinvent-the-wheel",
      theme: "light",
      chapter: "Do not reinvent the wheel",
      title: "Do not reinvent the **wheel**.",
      marker: "bullet",
      split: "golden-flip",
      points: [
        "Usability research — decades of it, and almost none of it yours",
        "Platform conventions — what the OS already taught your user",
        "Accessibility standards — normative, and not a matter of taste",
        "Interaction principles — why a control behaves the way it does",
        "Iteration with real users — the part no reference can hand you",
        "Following a proven convention is not plagiarism. Lifting a whole design system is.",
      ],
    },
    {
      type: "cards",
      id: "look-past-the-first-reference",
      chapter: "Look past the first reference",
      title: "Look past the first reference that looks **good**.",
      note: "Read them for the recurring pattern — hierarchy, spacing, typography, navigation, interaction, content density, rhythm. The goal is not to copy a screen; it is to see why a good screen feels right.",
      cards: [
        {
          title: "Product flows",
          subtitle: "What the screen does next",
          points: [
            "[Mobbin](https://mobbin.com) · [Pageflows](https://pageflows.com) · [ScreensDesign](https://screensdesign.com)",
            "Whole flows, not single screens. The states between them are what a still never shows you.",
          ],
        },
        {
          title: "Visual inspiration",
          subtitle: "How it looks, and how it feels",
          points: [
            "[Dribbble](https://dribbble.com) · [Behance](https://behance.net) · [Godly](https://godly.website) · [Awwwards](https://awwwards.com)",
            "Strong on treatment, weak on product logic. Take the surface, leave the structure.",
          ],
        },
        {
          title: "Landing pages",
          subtitle: "How it sells itself",
          points: [
            "[Landingfolio](https://landingfolio.com)",
            "One page, one job. The order of the sections is the argument the page is making.",
          ],
        },
      ],
    },
    {
      type: "table",
      id: "not-every-rule-binds-the-same-way",
      chapter: "Not every rule binds the same way",
      title: "Not every rule **binds** the same way.",
      note: "Which level a number comes from decides how much trust it earns, and how hard to argue when an agent cites it at you.",
      columns: [
        "Level",
        "How much it binds",
        "Source & example",
      ],
      rows: [
        {
          severity: "Requirements",
          tone: "red",
          meaning: "Must. An audit fails without it.",
          examples: "[WCAG 2.2](https://www.w3.org/TR/WCAG22) — 4.5:1 body contrast · 24×24px targets, with listed exceptions",
        },
        {
          severity: "Guidelines",
          tone: "orange",
          meaning: "Should. What the platform expects.",
          examples: "[Apple HIG](https://developer.apple.com/design) — at least 44×44pt for a touch target",
        },
        {
          severity: "Heuristics",
          tone: "yellow",
          meaning: "Consider. A study, not a threshold.",
          examples: "[Laws of UX](https://lawsofux.com) — feedback inside ~400ms · [designparser](https://designparser.de) — 50–75ch measure",
        },
      ],
    },
    {
      type: "codeui",
      id: "measure-what-can-be-measured",
      chapter: "Measure what can be measured",
      title: "Measure what can be **measured**.",
      file: "DESIGN.md",
      lang: "md",
      code: "## Review contract\n\nrequired   contrast >= 4.5:1 body    WCAG 1.4.3\nrequired   target >= 24x24px         WCAG 2.5.8\nguideline  target >= 44x44pt on iOS  Apple HIG\nheuristic  measure 50-75ch body      designparser\nheuristic  feedback under 400ms      Laws of UX\nconvention animate transform/opacity  DESIGN.md\n\njudged     hierarchy, clarity, density,\n           appropriateness, perceived complexity\n\nReport every failure as:\nmetric or evidence \u00b7 severity \u00b7 fix",
      preview: {
        title: "What comes back, per failure",
        buttons: [],
        rows: [
          { label: "metric", detail: "The threshold and the measured value, where one exists." },
          { label: "evidence", detail: "A screenshot, or the file and line. Required where no metric does." },
          { label: "severity", detail: "Blocking, major, minor, or polish." },
          { label: "fix", detail: "Concrete, or the agent invents one." },
        ],
      },
      note: "It lives beside the tokens in ```DESIGN.md```, so every session reads it. Contrast and target size are arithmetic and any agent can answer them. Hierarchy, clarity and perceived complexity are not — those come back evidence-based, and the evidence is what makes them arguable instead of a mood.",
    },
    {
      type: "cards",
      id: "what-this-looks-like-in-impeccable",
      chapter: "What this looks like in Impeccable",
      title: "What this looks like in **Impeccable**.",
      note: "Impeccable is one example of turning design principles into a repeatable review process.",
      cards: [
        {
          title: "/impeccable document",
          subtitle: "Define the design rules",
          points: [
            "Reads the existing product and design system",
            "Turns design decisions into a reusable DESIGN.md",
          ],
        },
        {
          title: "/impeccable critique",
          subtitle: "Review the design",
          points: [
            "Identifies usability and visual design issues",
            "Explains why they matter and suggests improvements",
          ],
        },
        {
          title: "/impeccable audit",
          subtitle: "Run objective checks",
          points: [
            "Checks things that can be measured consistently",
            "Covers areas such as accessibility, structure, and interaction",
          ],
        },
      ],
    },
    {
      type: "keypoints",
      id: "know-right-to-know-wrong",
      chapter: "Know right to know wrong",
      title: "You need to know what is **right** to know what is wrong.",
      marker: "bullet",
      points: [
        "Principles tell you why it works",
        "Conventions tell you what users already expect",
        "References expand what you can imagine",
        "Pick the metric before you evaluate the screen",
        "Run the checks each pass, not once at the end",
      ],
    },
    {
      type: "divider",
      id: "my-working-loop",
      chapter: "My working loop",
      number: "04",
      split: "golden-flip",
      marker: "bullet",
      title: "My working **loop** (for now).",
      note: "The commands in it change every few months, as the tools do. What does not change is the shape: every pass ends by deciding whether to go round again.",
      list: [],
    },
    {
      type: "process",
      id: "four-steps-and-the-way-back",
      chapter: "Four steps, and the way back",
      title: "Four steps, and the way **back**.",
      loop: "back to shape or design when review lands there",
      steps: [
        {
          n: "01",
          tone: "teal",
          title: "Shape",
          via: "Agree",
          points: [
            "UX and behaviour, before anything is drawn",
            "PRODUCT.md and DESIGN.md are already written: once per project, not per pass",
          ],
        },
        {
          n: "02",
          tone: "blue",
          title: "Design",
          via: "Build",
          points: [
            "Refine what exists, or set the direction",
            "Hierarchy and flow settled before any polish",
          ],
        },
        {
          n: "03",
          tone: "violet",
          title: "Implement",
          via: "Check",
          points: [
            "The one step that is still mine",
            "Small enough that one review can cover it",
          ],
        },
        {
          n: "04",
          tone: "ink",
          title: "Review",
          points: [
            "Show a screenshot; describing the defect is slower",
            "A second model is fresh context, not a verdict",
            "A finding that lands on the shape sends it back to 01",
          ],
        },
      ],
    },
    {
      type: "codeui",
      id: "the-same-loop-in-commands",
      chapter: "The same loop, in commands",
      title: "The same loop, in **commands**.",
      file: "the-loop.sh",
      code: "# once per project\n/impeccable init         -> PRODUCT.md\n/impeccable document     -> DESIGN.md\n\n# every pass\n/impeccable shape <feature>\n  -> /design-taste-frontend\n     or /redesign-existing-projects\n  -> Implement\n  -> /impeccable critique <feature>\n  -> /impeccable audit <feature>\n  -> /impeccable polish <feature>\n\n# a finding on the shape -> back to shape\n# a finding on the look  -> back to the taste skill",
      preview: {
        title: "What each command is for",
        buttons: [],
        rows: [
          { label: "init", detail: "Writes PRODUCT.md. Once per project." },
          { label: "document", detail: "Reads the code, writes DESIGN.md." },
          { label: "shape", detail: "UX and behaviour, before any visual work." },
          { label: "taste skill", detail: "The branch: refine, or set a direction." },
          { label: "critique", detail: "Findings, each with a severity and a fix." },
          { label: "audit", detail: "The measurable checks, run per screen." },
          { label: "polish", detail: "The last pass before it is called done." },
        ],
      },
      note: "Two commands set the project up and are not run again. The rest are the pass, and one step in it is still mine: ```Implement``` is where the code gets written, and everything around it decides what gets written and whether it worked.",
    },
    {
      type: "cards",
      id: "refine-or-set-a-new-direction",
      chapter: "Refine, or set a new direction",
      title: "Refine what exists, or set a new **direction**.",
      note: "One branch in the loop, and the choice is about how much should change. Reach for design-taste when the direction itself is the problem.",
      cards: [
        {
          title: "/redesign-existing-projects",
          subtitle: "Refine what is already there",
          points: [
            "Audits the screen before it changes anything",
            "Fixes layout, spacing and hierarchy",
            "Ask it: ```Improve <feature> visually without changing its functionality or UX structure.```",
          ],
        },
        {
          title: "/design-taste-frontend",
          subtitle: "Set a new or stronger direction",
          points: [
            "For a direction that is missing or too weak to refine",
            "Sets the direction the later passes hold to",
            "Ask it: ```Improve the visual direction while preserving the existing brand and product structure.```",
          ],
        },
      ],
    },
    {
      type: "showcase",
      id: "use-a-fresh-model-as-a-second-opinion",
      chapter: "A fresh model as second opinion",
      title: "Use a fresh model as a **second opinion**.",
      note: "Do not ask another agent for a prettier version. Send the screen as it is, ask for concrete issues and a rendered alternative, then decide which of the fixes belong in your product.",
      images: [
        {
          src: "showcase/treeqr-shipped.png",
          alt: "The shipped 4-Season QR screen: a generated QR code, a full-width music transport bar under it, and one card holding the season tabs, six colour swatches, a URL field and three equal buttons.",          
        },
        {
          src: "showcase/treeqr-hardened.png",
          alt: "The revised flow: eight screens, each with a titled header, labelled sections for URL, Season and Tree Theme, and a single filled primary button.",          
        },
      ],
      points: [
        "Hierarchy — the music bar outweighs the card that does the job",
        "Control weight — tabs, swatches and three buttons all equal, and nothing is primary",
        "Unclear relationship — the tap hint collides with the URL field",
      ],    
    },
    {
      type: "keypoints",
      id: "how-you-run-the-loop",
      chapter: "How you run the loop",
      title: "How **you** run the loop.",
      marker: "bullet",
      split: "golden-flip",
      points: [
        "Write the spec once per project, not per pass",
        "Agree the shape before anyone touches the visual pass",
        "Branch on how much should change: refine, or redirect",
        "Keep each pass small enough that one review can cover it — implementing is still yours",
        "Review on evidence, and let a second model find what you stopped seeing",
        "When a finding lands on the shape, go back to it — that is the loop",
      ],
    },
    {
      type: "divider",
      id: "part-5",
      chapter: "Part 5",
      number: "05",
      title: "Hidden gems, not **hype**.",
      note: "As of September 2026. Five things worth the install, one starter set of three, and four references to keep open in a tab. Every one has a date on it, so you can see what is still moving.",
      list: [
        "Five tools, and what each is for",
        "A starter three",
        "Four references worth a bookmark",
        "What to take away",
      ],
    },
    {
      type: "divider",
      id: "part-5-placeholder",
      chapter: "To be written",
      title: "To be **written**.",
    },
    {
      type: "keypoints",
      id: "everything-here-has-a-link",
      chapter: "Everything here has a link",
      standalone: true,
      title: "Everything here has a **link**.",
      points: [
        "moelkholy1995.medium.com, the anti-slop article",
        "impeccable.style · tasteskill.dev · github.com/emilkowalski/skills",
        "skillui.vercel.app · getdesign.md · design.md spec, Google Labs",
        "designparser.de · lawsofux.com",
        "developer.apple.com/design · w3.org/TR/WCAG22",
      ],
    },
    {
      type: "quote",
      id: "shape-the-thinking",
      chapter: "Shape the thinking",
      standalone: true,
      quote: "Good AI design prompts shape the **thinking** that creates the screen.",
      closer: "Reduce ambiguity → Encode intent → Evaluate with evidence → Iterate deliberately.",
    },
  ],
} satisfies Deck

export default deck
