import DeckView from '../deck/DeckView'

/**
 * Sample — `content/sample.json`, review only; it is not what the app shows.
 *
 * Generated by scripts/lab-states.mjs. One screen per deck is what puts the
 * decks in the studio tree by name; the deck is fixed here so no state can
 * point this screen at a different one.
 */
export default function Sample(props) {
  return <DeckView {...props} deck="sample" />
}
