import type { ComponentProps } from 'react'
import DeckView from '../deck/DeckView'

/**
 * Sample — `content/sample.ts`, review only; it is not what the app shows.
 *
 * Generated by scripts/lab-states.ts. One screen per deck is what puts the
 * decks in the studio tree by name; the deck is fixed here so no state can
 * point this screen at a different one.
 */
export default function Sample(props: ComponentProps<typeof DeckView>) {
  return <DeckView {...props} deck="sample" />
}
