import DeckView from '../deck/DeckView'

/**
 * Version 1 — `content/version_1.json`, the deck that gets presented and published.
 *
 * Generated by scripts/lab-states.mjs. One screen per deck is what puts the
 * decks in the studio tree by name; the deck is fixed here so no state can
 * point this screen at a different one.
 */
export default function Version1(props) {
  return <DeckView {...props} deck="version_1" />
}
