#!/usr/bin/env node
/**
 * Regenerate the designlab states files from the active deck.
 *
 * The deck screen renders whatever `useContent()` returns, and its states pin a
 * content.json item **id**. So the moment the active deck changes — a new file,
 * a renamed item, a slide dropped — those ids name content that is not there
 * any more, `indexOfSlide` quietly falls back to the first slide, and every
 * capture of "the table slide" is a picture of the cover. Nothing errors. That
 * is the failure this script exists to prevent.
 *
 * It reads which deck is active out of `src/lib/useContent.js`, so there is one
 * source of truth for that and this script is not a second place to update.
 *
 *   npm run lab:states          rewrite the states files
 *   npm run lab:states -- --check   exit 1 if they are stale (no writes)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const check = process.argv.includes('--check')

/** The active deck, read from the one line that declares it. */
function activeDeckPath() {
  const src = readFileSync(resolve(root, 'src/lib/useContent.js'), 'utf8')
  const m = src.match(/^import\s+deck\s+from\s+'(.+?)'/m)
  if (!m) throw new Error('src/lib/useContent.js has no `import deck from ...` line to read')
  return resolve(root, 'src/lib', m[1])
}

const deckPath = activeDeckPath()
const deck = JSON.parse(readFileSync(deckPath, 'utf8'))
const items = deck.items || []
if (items.length === 0) throw new Error(`${deckPath} declares no items`)

const missing = items.filter((it) => !it.id)
if (missing.length) {
  throw new Error(
    `every item needs an \`id\` — a state pins ids, not indexes. ${missing.length} without one ` +
      `(types: ${[...new Set(missing.map((i) => i.type))].join(', ')})`,
  )
}

const ARCHETYPES = {
  cover: ['Cover', 'Dark. Headline with the accent word, over the dot sphere.'],
  divider: ['Section divider', 'Light. Big numeral, section title, and the numbered list of what is in it.'],
  keypoints: ['Key points', 'Dark. Title on the left, numbered rows hairline-separated on the right.'],
  twocolumn: ['Two column', 'Light. Two mock screens side by side, each under its own caption.'],
  process: ['Process', 'Light. Tone-coded step cards in a row, each over its own points.'],
  codeui: ['Code and UI', 'Light. Highlighted source in a tabbed pane beside the rendered result.'],
  table: ['Table', 'Light. A matrix with tone-coded severity and action columns.'],
  quote: ['Quote', 'Light. Oversized quote mark, the line itself, and the closer beside it.'],
}

/** One example item per archetype, so a variant shows what an author gets. */
const byType = new Map()
for (const it of items) if (!byType.has(it.type)) byType.set(it.type, it)

// ---------------------------------------------------------------- deck screen
const deckStates = items.map((it, n) => ({
  id: `slide-${it.id}`,
  label: `${String(n + 1).padStart(2, '0')} · ${it.type}`,
  note: `The ${it.type} archetype in the deck shell, with the chrome and page reference around it.`,
  params: { slide: it.id },
}))

deckStates.push(
  {
    id: 'contents-outline',
    label: 'Contents · outline',
    note: 'The contents panel over the first slide, on the Outline tab: every slide with its sub-rows.',
    params: { slide: items[0].id, contents: 'outline' },
  },
  {
    id: 'contents-slides',
    label: 'Contents · slides',
    note: 'The same panel on the Slides tab: themed thumbnails, the current one marked.',
    params: { slide: items[0].id, contents: 'slides' },
  },
  {
    id: 'empty',
    label: 'No slides',
    note: 'A deck file with an empty items array. Nothing else can reach this copy.',
    params: { status: 'empty' },
  },
)

const deckDoc = {
  screen: 'deck',
  title: 'Deck',
  group: 'Deck',
  mood: 'capture',
  note:
    'The presented deck. A state pins a content.json item id, not an index, so reordering the deck ' +
    'does not repoint every capture. Generated by scripts/lab-states.mjs from the active deck — ' +
    'run `npm run lab:states` after changing content.',
  params: [
    {
      id: 'slide',
      label: 'slide',
      default: items[0].id,
      options: items.map((it) => ({ id: it.id, label: `${it.id} · ${it.type}` })),
    },
    {
      id: 'contents',
      label: 'contents',
      default: 'closed',
      options: [
        { id: 'closed', label: 'Closed' },
        { id: 'outline', label: 'Outline' },
        { id: 'slides', label: 'Slides' },
      ],
    },
    {
      id: 'status',
      label: 'status',
      default: 'ready',
      options: [
        { id: 'ready', label: 'Ready' },
        { id: 'empty', label: 'No slides' },
      ],
    },
  ],
  states: deckStates,
}

// ------------------------------------------------------------ slide archetypes
const slideStates = []
for (const [type, it] of byType) {
  const [label, note] = ARCHETYPES[type] || [type, `The ${type} archetype.`]
  slideStates.push({ id: type, label, device: 'desktop', note, props: { item: it, still: true } })
}

// The dispatcher falls back to Divider for a type it does not know, and that
// fallback is only ever seen here.
slideStates.push({
  id: 'unknown-type',
  label: 'Unknown type',
  device: 'desktop',
  note: 'An item whose `type` is not in the map. Slide falls back to Divider rather than rendering nothing.',
  props: { item: { ...items[0], id: 'unknown-type', type: 'not-a-real-type' }, still: true },
})

// The narrow check, for the archetypes whose multi-column grid a phone breaks.
for (const type of ['cover', 'keypoints', 'twocolumn', 'process', 'table']) {
  const it = byType.get(type)
  if (!it) continue
  slideStates.push({
    id: `${type}-phone`,
    label: `${(ARCHETYPES[type] || [type])[0]} · phone`,
    device: 'iphone',
    note: 'The same archetype at 393px, where its grid has to give.',
    props: { item: it, still: true },
  })
}

const slideDoc = {
  component: 'Slide',
  title: 'Slide archetypes',
  group: 'Slides',
  order: 1,
  mood: 'capture',
  note:
    'The archetypes a deck is built from. Props are real items from the active deck, so a variant ' +
    'shows what an author actually gets. Generated by scripts/lab-states.mjs.',
  states: slideStates,
}

// ------------------------------------------------------------------- write out
const targets = [
  ['src/screens/Deck.states.json', deckDoc],
  ['src/components/Slide/Slide.states.json', slideDoc],
]

let stale = 0
for (const [rel, doc] of targets) {
  const path = resolve(root, rel)
  const next = JSON.stringify(doc, null, 2) + '\n'
  let current = ''
  try {
    current = readFileSync(path, 'utf8')
  } catch {
    /* not there yet */
  }
  if (current === next) {
    console.log(`  up to date  ${rel}`)
    continue
  }
  stale++
  if (check) {
    console.error(`  STALE       ${rel}`)
  } else {
    writeFileSync(path, next)
    console.log(`  wrote       ${rel}`)
  }
}

const deckRel = deckPath.slice(root.length + 1)
console.log(`\nactive deck: ${deckRel} — ${items.length} items, ${byType.size} archetypes`)

if (check && stale) {
  console.error(`\n${stale} states file(s) do not match ${deckRel}. Run \`npm run lab:states\`.`)
  process.exit(1)
}
